name: Tests Automatiques

# Quand est-ce que le robot doit se réveiller ?
on:
  push:
    branches: [ "main", "younes-jebari" ]
  pull_request:
    branches: [ "main" ]

# Ce que le robot doit faire :
jobs:
  test:
    runs-on: ubuntu-latest # Il utilise un ordinateur virtuel sous Linux

    steps:
    # Étape 1 : Il télécharge votre code
    - name: Récupération du code
      uses: actions/checkout@v4

    # Étape 2 : Il installe Python 3.12
    - name: Configuration de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    # Étape 3 : Il installe vos bibliothèques (pandas, pytest, etc.)
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 4 : Il lance la vérification
    - name: Lancement des tests
      run: |
        pytest tests/